server:
  port: 9999

spring:
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  datasource:
    url: jdbc:mysql://106.52.14.170:3306/tms?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  activiti:
    check-process-definitions: false
    database-schema: update


mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: org.java.entity

